apiVersion: platform.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: test-db
  namespace: demo-db
spec:
  parameters:
    storageGB: 32
    location: northeurope
    resourceGroupName: platform-eng-rg