apiVersion: v1
kind: Service
metadata:
  name: team-beta-api
  namespace: team-beta-api
  labels:
    app: team-beta-api
spec:
  selector:
    app: team-beta-api
  ports:
    - name: http
      port: 80
      targetPort: 8080